//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveMealAd
    {
        public int MealAdID { get; set; }
        public string MealItemName { get; set; }
        public System.DateTime PickUpTime { get; set; }
        public int MaxOrders { get; set; }
        public int PlacedOrder { get; set; }
        public System.DateTime LastOrderTime { get; set; }
        public string CuisineType { get; set; }
        public string MealType { get; set; }
        public string Description { get; set; }
        public string Ingredients { get; set; }
        public string Photo { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string FoodAllergy { get; set; }
        public string FoodType { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string latlng { get; set; }
        public string PriceRange { get; set; }
        public string AllInfo { get; set; }
        public string ProviderType { get; set; }
        public string ProviderName { get; set; }
        public string FullAddress { get; set; }
    }
}
