//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllEmail
    {
        public int EmailID { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string CCAddress { get; set; }
        public string BCCAddress { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBodyText { get; set; }
        public System.DateTime SendDate { get; set; }
        public string EmailStatus { get; set; }
        public string Comment { get; set; }
    }
}
