//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int RecordID { get; set; }
        public string CartID { get; set; }
        public int MealAdID { get; set; }
        public int Count { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual MealAd MealAd { get; set; }
    }
}
