//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactList
    {
        public int ContactListID { get; set; }
        public int UserID { get; set; }
        public string SenderEmailAddress { get; set; }
        public Nullable<int> RecipientUserID { get; set; }
        public string RecipientEmailAddress { get; set; }
        public Nullable<int> RequestAccepted { get; set; }
    }
}
