//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunOrder
    {
        public FunOrder()
        {
            this.FunOrderDetails = new HashSet<FunOrderDetail>();
        }
    
        public int UserId { get; set; }
        public System.DateTime EstimatedPickupTime { get; set; }
        public Nullable<System.DateTime> ActualPickUpTime { get; set; }
        public Nullable<int> FeedbackOnTime { get; set; }
        public string GeneralFeedback { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int Status { get; set; }
        public int OrderID { get; set; }
        public decimal Total { get; set; }
        public int PaymentOptionID { get; set; }
        public int DeliveryMethodID { get; set; }
    
        public virtual ICollection<FunOrderDetail> FunOrderDetails { get; set; }
    }
}
