//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunOrderDetail
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> FeedbackOnQuality { get; set; }
        public Nullable<int> FeedbackOnPrice { get; set; }
        public int OrderID { get; set; }
    
        public virtual FunOrder FunOrder { get; set; }
    }
}
