//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPServingUnit
    {
        public LKUPServingUnit()
        {
            this.MealItems = new HashSet<MealItem>();
        }
    
        public int ServingUnitID { get; set; }
        public string ServingUnit { get; set; }
    
        public virtual ICollection<MealItem> MealItems { get; set; }
    }
}
