//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPAllergenicFood
    {
        public LKUPAllergenicFood()
        {
            this.MealItems_AllergenicFoods = new HashSet<MealItems_AllergenicFoods>();
        }
    
        public int AllergenicFoodID { get; set; }
        public string AllergenicFood { get; set; }
    
        public virtual ICollection<MealItems_AllergenicFoods> MealItems_AllergenicFoods { get; set; }
    }
}
