//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPCountry
    {
        public LKUPCountry()
        {
            this.AddressLists = new HashSet<AddressList>();
        }
    
        public int CountryID { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string CurrencyAbbreviation { get; set; }
        public string IdentificationType { get; set; }
        public string CountryAbbr { get; set; }
    
        public virtual ICollection<AddressList> AddressLists { get; set; }
    }
}
