//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPDeliveryMethod
    {
        public LKUPDeliveryMethod()
        {
            this.MealAds_DeliveryMethods = new HashSet<MealAds_DeliveryMethods>();
        }
    
        public int DeliveryMethodID { get; set; }
        public string DeliveryMethod { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MealAds_DeliveryMethods> MealAds_DeliveryMethods { get; set; }
    }
}
