//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPMealType
    {
        public LKUPMealType()
        {
            this.MealItems = new HashSet<MealItem>();
        }
    
        public int MealTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual ICollection<MealItem> MealItems { get; set; }
    }
}
