//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAd
    {
        public MealAd()
        {
            this.Carts = new HashSet<Cart>();
            this.MealAds_DeliveryMethods = new HashSet<MealAds_DeliveryMethods>();
            this.MealAds_PaymentOptions = new HashSet<MealAds_PaymentOptions>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.MealAd_Schedules = new HashSet<MealAd_Schedules>();
        }
    
        public int MealAdID { get; set; }
        public int MealItemID { get; set; }
        public int MaxOrders { get; set; }
        public int PlacedOrder { get; set; }
        public int AvailabilityTypeID { get; set; }
        public int Status { get; set; }
    
        public virtual AvailabilityType AvailabilityType { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<MealAds_DeliveryMethods> MealAds_DeliveryMethods { get; set; }
        public virtual MealItem MealItem { get; set; }
        public virtual MealItem MealItem1 { get; set; }
        public virtual ICollection<MealAds_PaymentOptions> MealAds_PaymentOptions { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<MealAd_Schedules> MealAd_Schedules { get; set; }
    }
}
