//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAd_Schedules
    {
        public int MealAdScheduleID { get; set; }
        public int MealAdID { get; set; }
        public System.DateTime PickUpStartDateTime { get; set; }
        public System.DateTime PickUpEndDateTime { get; set; }
        public System.DateTime LastOrderDateTime { get; set; }
    
        public virtual MealAd MealAd { get; set; }
    }
}
