//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAds_DeliveryMethods
    {
        public int MealAd_DeliveryMethodID { get; set; }
        public int DeliveryMethodID { get; set; }
        public int MealAdID { get; set; }
    
        public virtual LKUPDeliveryMethod LKUPDeliveryMethod { get; set; }
        public virtual MealAd MealAd { get; set; }
    }
}
