//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealItems_AllergenicFoods
    {
        public int AllergenicFoodID { get; set; }
        public int MealItemID { get; set; }
        public int MealItem_AllergenID { get; set; }
    
        public virtual LKUPAllergenicFood LKUPAllergenicFood { get; set; }
        public virtual MealItem MealItem { get; set; }
    }
}
