//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOption
    {
        public PaymentOption()
        {
            this.MealAds_PaymentOptions = new HashSet<MealAds_PaymentOptions>();
        }
    
        public int PaymentOptionID { get; set; }
        public string PaymentOption1 { get; set; }
    
        public virtual ICollection<MealAds_PaymentOptions> MealAds_PaymentOptions { get; set; }
    }
}
