//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerDefaultSetting
    {
        public int SellerSettingID { get; set; }
        public int userid { get; set; }
        public Nullable<int> OrderFulfillmentTime { get; set; }
        public Nullable<int> UnitOfTime { get; set; }
        public Nullable<int> Delivery { get; set; }
        public Nullable<int> Shipping { get; set; }
        public Nullable<int> PickUp { get; set; }
        public Nullable<int> AcceptCard { get; set; }
        public Nullable<int> AcceptCashOnDelivery { get; set; }
        public Nullable<int> HasPermit { get; set; }
        public Nullable<int> Permit { get; set; }
        public string PermitImage { get; set; }
    }
}
