//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendEmail
    {
        public int SendEmailID { get; set; }
        public string SenderEmailAddress { get; set; }
        public string RecipientEmailAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public string DeliveryMethod { get; set; }
        public string Status { get; set; }
        public System.DateTime SendDate { get; set; }
    }
}
