//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int state_id { get; set; }
        public string state_name { get; set; }
        public string state_abbrev { get; set; }
        public Nullable<int> countryid { get; set; }
    }
}
