//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrderList
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string sessionId { get; set; }
        public string MealItemId { get; set; }
        public string itemName { get; set; }
        public decimal lineitemcost { get; set; }
        public int qty { get; set; }
        public decimal TotalCost { get; set; }
    }
}
