//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int UserStatus { get; set; }
        public string Notes { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string AllInfo { get; set; }
        public int AddressID { get; set; }
        public Nullable<int> GoogleCheckoutID { get; set; }
        public Nullable<int> PayPalID { get; set; }
        public Nullable<int> AmazonPayID { get; set; }
        public string SkypeID { get; set; }
        public string Mobile { get; set; }
        public string IdentificationNumber { get; set; }
        public string PassportNumber { get; set; }
        public string CountryOfIssuance { get; set; }
        public Nullable<int> IsSeller { get; set; }
        public string KitchenName { get; set; }
        public Nullable<int> KitchenTypeID { get; set; }
        public int SellersTermsAndConditionAccepted { get; set; }
    
        public virtual AddressList AddressList { get; set; }
        public virtual AddressList AddressList1 { get; set; }
        public virtual LKUPKitchenType LKUPKitchenType { get; set; }
    }
}
