//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAgreementsAcceptanceDetail
    {
        public int UserAgreementID { get; set; }
        public int AgreementID { get; set; }
        public int UserID { get; set; }
        public System.DateTime AgreementAccepetedOn { get; set; }
    }
}
