//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentOption
    {
        public int PaymentOptionID { get; set; }
        public int UserId { get; set; }
        public string PaymentType { get; set; }
        public int PaymentID { get; set; }
    }
}
